FrogFeeder:
  Enabled: true
  Cooldown: 1
  AngryChance: 0.2
  ParticleMin: 10
  ParticleMax: 25
  AprilFools: false

ArmorReseter:
  Enabled: true
  AnvilDamageChance: 0.12
  ArmorBreakChance: 0.5
  MinDurabilityLoss: 3
  MaxDurabilityLoss: 14

ToolStats:
  Enabled: true
  UpdateInterval: 2
  
  # Доступные плейсхолдеры для инструментов и оружия:
  # %blocks% - количество добытых блоков
  # %kills% - количество убитых мобов
  # %maxdamage% - максимальный урон за один удар
  # %alldamage% - весь нанесенный урон
  # %oneshots% - количество ваншотов
  # %shots% - количество выпущенных снарядов
  # %distance% - пролетная дистанция в метрах
  # %xp_spent% - потраченный опыт на починку
  # %full_repairs% - количество полных починок до максимума
  
  # Доступные плейсхолдеры для брони:
  # %hits% - количество полученных ударов
  # %absorbed% - поглощенный урон
  # %reflected% - отраженный урон
  
  # Доступные плейсхолдеры для щита:
  # %blocked_hits% - количество заблокированных ударов
  # %blocked_damage% - заблокированный урон
  
  InfoPickaxe:
    Enabled: true
    Lines:
  
  InfoAxe:
    Enabled: true
    Lines:
  
  InfoShovel:
    Enabled: true
    Lines:
  
  InfoHoe:
    Enabled: true
    Lines:
  
  InfoSword:
    Enabled: true
    Lines:
  
  InfoMace:
    Enabled: true
    Lines:
  
  InfoStick:
    Enabled: true
    Lines:
  
  InfoBow:
    Enabled: true
    Lines:
  
  InfoCrossbow:
    Enabled: true
    Lines:
  
  InfoElytra:
    Enabled: true
    Lines:
  
  InfoShield:
    Enabled: true
    Lines:
  
  InfoHelmet:
    Enabled: true
    Lines:
  
  InfoChestplate:
    Enabled: true
    Lines:
  
  InfoLeggings:
    Enabled: true
    Lines:
  
  InfoBoots:
    Enabled: true
    Lines:

WoodStonecutter:
  Enabled: true

FastLeafDecay:
  Enabled: true
  MaxLeaves: 20
  MinDelayTicks: 2
  MaxDelayTicks: 10

ConcreteHardener:
  Enabled: true
  AmountPerLevel: 8
  CooldownSeconds: 2

OxidizeCopper:
  Enabled: true
  BottleAccelerationMultiplier: 20
